Custom map names convert
ParadoxGameConverters/CK3toEU4 pull request #330
Opened 2022-04-18 19:45 UTC by gawquon

Have CK3 counties with player overridden names transfer to their associated EU4 provinces in a sensible manner.
Also patch some typos and such in tradition_ideas.txt.

2022-04-18 20:04 UTC, Zemurin requested changes
I'd also love to see some tests showing how renaming is done if possible.

2022-04-18 20:04 UTC, Zemurin commented on CK3toEU4/Source/EU4World/Province/EU4Province.cpp
> +	mappers::LocDegraderMapper;
What's going on here?

2022-04-18 20:04 UTC, Zemurin commented on CK3toEU4/Source/EU4World/Province/EU4Province.cpp
> +		auto name = locDegrader.degradeString(srcProvince->getDisplayName());
Locdegrader might not do anything on - say - cyrillic inputs. Yo should try renaming provinces into chinese and see what happens in eu4, just to be on the safe side.

2022-04-19 00:48 UTC, Idhrendur commented on CK3toEU4/Source/CK3World/Titles/Title.cpp
> +		renamed = isRenamed == "yes";
```suggestion
		renamed = commonItems::getString(theStream)== "yes";
```

2022-04-19 00:48 UTC, Idhrendur commented on CK3toEU4/Source/EU4World/EU4World.cpp
> +	}
In addition to the comment from @Zemurin, if you place this all in a small function you can use guard clauses for the checks and avoid deep nesting: https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2022-04-27 12:17 UTC, Wielislaw commented
If it actually works, then it could and should be implemented to the rest of the converters.

2022-06-01 11:07 UTC, Zemurin requested changes
Just cosmetics.

2022-06-01 11:07 UTC, Zemurin commented on CK3toEU4/Source/EU4World/Province/EU4Province.cpp
> +	// check for manual CK3 province name
Was there a check supposed to be here?

2022-06-01 11:07 UTC, Zemurin commented on CK3toEU4/Source/CK3World/Titles/Title.cpp
> +void CK3::Title::pickDisplayName(const std::map<std::string, std::shared_ptr<Title>>& mappings)
Please don't use generic "mappings" but something more appropriate like "availableTitles" or such.

2022-06-01 11:30 UTC, Zemurin approved these changes

2022-06-01 11:36 UTC, merged